site_name: Andal Docs
site_url: https://rlaksana.github.io/andal-docs/
theme:
  name: material

plugins:
  - search
  - awesome-pages

nav:
  - Home: index.md
  - Futaba:
      - Sheet 1:
        - Finding 8: Futaba/Sheet 1/Finding 8.md
        - Finding 9: Futaba/Sheet 1/Finding 9.md
        - Finding 10: Futaba/Sheet 1/Finding 10.md
        - Finding 11: Futaba/Sheet 1/Finding 11.md
        - Finding 12: Futaba/Sheet 1/Finding 12.md
        - Finding 13: Futaba/Sheet 1/Finding 13.md
        - Finding 14: Futaba/Sheet 1/Finding 14.md
        - Finding 15: Futaba/Sheet 1/Finding 15.md
        - Finding 16: Futaba/Sheet 1/Finding 16.md
        - "Finding 17-22": "Futaba/Sheet 1/Finding 17, 18, 19, 20, 21, 22.md"
        - Finding 86: Futaba/Sheet 1/Finding 86.md
        - Finding 87: Futaba/Sheet 1/Finding 87.md
      - Sheet 2:
        - Finding 1: Futaba/Sheet 2/Finding 1.md
        - Finding 7: Futaba/Sheet 2/Finding 7.md
        - Finding 8: Futaba/Sheet 2/Finding 8.md

docs_dir: docs
