name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Clean site directory
        run: rm -rf site

      - name: Build documentation
        run: mkdocs build

      - name: List site contents  # Check if files exist
        run: ls -l site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages
          folder: site
