name: Deploy MkDocs

on:
  push:
    branches:
      - main

# Prevent concurrent deploys to avoid conflicts
concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write  # Required for artifact uploads

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin

      - name: Clean site directory
        run: rm -rf site

      - name: Build documentation
        run: mkdocs build

      - name: List site contents 
        run: |
          ls -la site
          find site -type f

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
