name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write   # Allow writing files to the repository
  pages: write      # Allow publishing to GitHub Pages
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Clean site directory
        run: rm -rf site

      - name: Build documentation
        run: mkdocs build

      - name: List site contents 
        run: ls -l site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site 

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages
          artifact_name: github-pages
